channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=25.0.1
- pip:
  - mlflow==2.21.0
  - cloudpickle==3.1.1
  - graphviz==0.20.3
  - lightgbm==4.6.0
  - matplotlib==3.10.1
  - numpy==1.26.4
  - pandas==2.2.3
  - pyarrow==19.0.1
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
